# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CLI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

jobs:
  generate_sln:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Get Release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'GlitchedFlow/luna-build'
          version: 'tags/v1.0'
          file: 'v1.0_Luna.zip'
      - name: Unzip Release
        run: 7z x v1.0_Luna.zip
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build Solution
        run: ls
      - name: Upload Solution
        uses: actions/upload-artifact@master
        with:
          name: solution-artifact
          path: ./solution
      - name: Remove zip
        run: rm v1.0_Luna.zip
          
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ linux-latest, windows-latest, macos-latest ]

    steps:
      - name: Wait
        uses: NathanFirmo/wait-for-other-job@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job: 'generate_sln'
          failOnJobError: true
      - name: Get Solution
        uses: actions/download-artifact@master
        with:
          name: solution-artifact
          path: ./solution
      - name: Build CLI
        run: dotnet ./solution/Windows/CLI/CLI.csproj
  
